# Example configuration file for AIDE.

@@define DBDIR /usr/lib/aide
@@define LOGDIR /usr/lib/aide/logs

# The location of the database to be read.
database_in=file:@@{DBDIR}/aide.db.gz

# The location of the database to be written.
#database_out=sql:host:port:database:login_name:passwd:table
#database_out=file:aide.db.new
database_out=file:@@{DBDIR}/aide.db.new.gz

# Whether to gzip the output to database
gzip_dbout=yes

# Default.
log_level=warning

report_url=file:@@{LOGDIR}/aide.log
report_url=stdout
#report_url=stderr
#NOT IMPLEMENTED report_url=mailto:root@foo.com
#NOT IMPLEMENTED report_url=syslog:LOG_AUTH

# These are the default rules.
#
#p:      permissions
#i:      inode:
#n:      number of links
#u:      user
#g:      group
#s:      size
#b:      block count
#m:      mtime
#a:      atime
#c:      ctime
#S:      check for growing size
#acl:           Access Control Lists
#selinux        SELinux security context
#xattrs:        Extended file attributes
#md5:    md5 checksum
#sha1:   sha1 checksum
#sha256:        sha256 checksum
#sha512:        sha512 checksum
#rmd160: rmd160 checksum
#tiger:  tiger checksum

#haval:  haval checksum (MHASH only)
#gost:   gost checksum (MHASH only)
#crc32:  crc32 checksum (MHASH only)
#whirlpool:     whirlpool checksum (MHASH only)

FIPSR = p+u+g+s+acl+xattrs+sha256

#R:             p+i+n+u+g+s+m+c+acl+selinux+xattrs+md5
#L:             p+i+n+u+g+acl+selinux+xattrs
#E:             Empty group
#>:             Growing logfile p+u+g+i+n+S+acl+selinux+xattrs

# You can create custom rules like this.
# With MHASH...
# ALLXTRAHASHES = sha1+rmd160+sha256+sha512+whirlpool+tiger+haval+gost+crc32
ALLXTRAHASHES = sha1+rmd160+sha256+sha512+tiger
# Everything but access time (Ie. all changes)
EVERYTHING = R+ALLXTRAHASHES

NORMAL = FIPSR+sha512

# For directories, don't bother doing hashes
DIR = p+u+g+acl+xattrs

# Access control only
PERMS = p+u+g+acl

# Logfile are special, in that they often change
LOG = >

# Some files get updated automatically, so the inode/ctime/mtime change
# but we want to know when the data inside them changes
DATAONLY =  p+u+g+s+acl+xattrs+sha256

# Next decide what directories/files you want in the database.

/bin    NORMAL
/boot   NORMAL
/home   NORMAL
/lib    NORMAL
/sbin   NORMAL
/opt    NORMAL
/usr    NORMAL

# Check only permissions, inode, user and group for /etc, but
# cover some important files closely.

/etc    PERMS
!/etc/mtab
!/etc/.pwd.lock

/etc/fstab    NORMAL
/etc/passwd   NORMAL
/etc/group    NORMAL
/etc/gshadow  NORMAL
/etc/shadow   NORMAL

/etc/sudoers NORMAL
/etc/sudoers.d NORMAL

/etc/profile NORMAL
/etc/login.defs NORMAL

/etc/modprobe.d NORMAL
/etc/pam.d NORMAL
/etc/ssh/sshd_config NORMAL
/etc/ssh/ssh_config NORMAL

/etc/init.d NORMAL
/etc/rc0.d NORMAL
/etc/rc1.d NORMAL
/etc/rc2.d NORMAL
/etc/rc3.d NORMAL
/etc/rc4.d NORMAL
/etc/rcS.d NORMAL
/etc/rc6.d NORMAL
/etc/rcS.d NORMAL

# AIDE will setup the initial database as an postinst task, and these are
# removed after the first boot, so don't track them
!/etc/rcS.d/S99run-postinsts
!/etc/rpm-postinsts/100-aide


# As AIDE changes it's database and create logs, it will
# always be considered new or changed from the previous update
!/usr/lib/aide
!/usr/lib/aide/logs
