# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sulka-distro"
BBFILE_PATTERN_meta-sulka-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sulka-distro = "11"

LAYERDEPENDS_meta-sulka-distro = "core networking-layer security"
LAYERDEPENDS_meta-sulka-distro:append = "${@" selinux " if d.getVar('SULKA_MANDATORY_ACCESS_CONTROL_MODULE') == "selinux" else ""}"


LAYERSERIES_COMPAT_meta-sulka-distro = "scarthgap"
