DISTRO = "sulka"
DISTRO_NAME = "Sulka"
DISTRO_VERSION = "0.6.0"
DISTRO_CODENAME = "Albatross"

TARGET_VENDOR = "-sulka"

SDK_VENDOR = "-sulkasdk"
SDK_VERSION="${DISTRO_VERSION}"

MAINTAINER = "ejaaskel <esa.jaaskela@suomi24.fi>"

LOCALCONF_VERSION = "2"

TCLIBCAPPEND = ""

PACKAGE_CLASSES ?= "package_rpm"

INIT_MANAGER ?= "systemd"

require conf/distro/include/no-static-libs.inc
require conf/distro/include/yocto-uninative.inc

INHERIT += "uninative"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"
BB_HASHSERVE ??= "auto"

require conf/distro/include/sulka-hardening.inc
