# Set SULKA_SERVICEUSER_ENABLE_SUDO="1" in your build configuration to uncomment lines below
# Note that this configuration allows all the commands for the service user, effectively making them a root user.
# You may want to consider overriding this serviceuser.conf in your own meta-layer with more fine-grained configuration.
# Defaults:@@SULKA_SERVICEUSER_USERNAME@@ secure_path="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
# @@SULKA_SERVICEUSER_USERNAME@@ ALL=(ALL:ALL) ALL
