# Uncomment the lines below to allow using sudo for the service user
Defaults:@@SULKA_SERVICEUSER_USERNAME@@ secure_path="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
@@SULKA_SERVICEUSER_USERNAME@@ ALL=(ALL:ALL) ALL
